<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Agenda [ 
<!ELEMENT Agenda (Persona)*> 
<!ELEMENT Persona (name,telephone,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>
<Agenda>
    <Persona>
        <name>ads</name>
        <telephone>564</telephone>
        <email>asd</email>
    </Persona>
</Agenda>
